service: participant

custom:
  settings:
    PARTICIPANT_TABLE: participant
   

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  environment: ${self:custom.settings}
  iamRoleStatements:
   - Effect: "Allow"
     Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
     Resource:
      - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.PARTICIPANT_TABLE}"

functions:
  createParticipant:
    handler: handler.createParticipant
    events:
    - http:
        path: /participant
        method: post
  getAllparticipants:
    handler: handler.getAllparticipant
    events:
    - http:
        path: /participants
        method: get
  getParticipantsByRoom:
    handler: handler.getParticipantByRoom
    events:
    - http:
        path: /room/participant
        method: post
  

resources:
  Resources:
    ParticipantTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "roomId"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "roomId"
          KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.PARTICIPANT_TABLE}
    